export enum SCREEN {
  LOGIN = 'LoginScreen',
  SIGNUP = 'SignupScreen',
  PROFILE = 'Profile',
  LOGO_SCREEN = 'Logo',
  HOME = 'Home',
  OFFER = 'Offer',
  CART = 'Cart',
  ONBOARDING_MODULE = 'Onboarding_module',
  SEARCH = 'Search',
  WELCOME_MODULES = 'Welcome_Screen',
  AUTH = 'Auth',
  SETTINGS = 'Settings',
  ORDERS = 'Orders',
  ADD_TO_CART = 'AddTo_Cart',
  RECENT_SEARCHES = 'Recent_searches',
  USERS_DETAILS = 'User_Details',
  USERS_PREFARENCES = 'User_Prefarences',
  EDITS_USERS_ACCOUNT = 'Edit_Account',
  ALL_RESTOURENT = 'All_Restourent',
  CHAT = 'Chat',
  BOOKMARKS = 'Bookmarks',
  NOTIFICATIONS = 'Notifications',
  PAYMENTS = 'Payments',
  DISSCOUNT_OFFERS = 'Disscount_offer',
  USER_DETAILS = 'User_details',
}
